//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalDictionary.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalDictionary.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;library&gt;
        ///  &lt;GlobalDictionary /&gt;
        ///  &lt;PersonalDictionaries /&gt;
        ///  &lt;TraingProgressApplest /&gt;
        ///&lt;/library&gt;.
        /// </summary>
        internal static string source_empty_dic {
            get {
                return ResourceManager.GetString("source_empty_dic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;library&gt;
        ///  &lt;GlobalDictionary&gt;
        ///    &lt;word id=&quot;1&quot; en=&quot;Word1&quot; ru=&quot;Слово1&quot; date_add=&quot;10.04.2018 13:05:04&quot; date_modified=&quot;10.04.2018 13:05:04&quot; /&gt;
        ///	  &lt;word id=&quot;2&quot; en=&quot;Word2&quot; ru=&quot;Слово2&quot; date_add=&quot;10.04.2018 13:05:04&quot; date_modified=&quot;10.04.2018 13:05:04&quot; /&gt;
        ///	  &lt;word id=&quot;3&quot; en=&quot;Word3&quot; ru=&quot;Слово3&quot; date_add=&quot;10.04.2018 13:05:04&quot; date_modified=&quot;10.04.2018 13:05:04&quot; /&gt;
        ///	  &lt;word id=&quot;4&quot; en=&quot;Word4&quot; ru=&quot;Слово4&quot; date_add=&quot;10.04.2018 13:05:04&quot; date_modified=&quot;10.04.2018 13:05:04&quot; /&gt; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string source_test4_dic {
            get {
                return ResourceManager.GetString("source_test4_dic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;library&gt;
        ///  &lt;GlobalDictionary&gt;
        ///    &lt;word id=&quot;1&quot; en=&quot;Word1&quot; ru=&quot;Слово1&quot; date_add=&quot;2018-04-10T13:05:04&quot; date_modified=&quot;10.04.2018 20:54:46&quot; /&gt;
        ///    &lt;word id=&quot;2&quot; en=&quot;Word2&quot; ru=&quot;Слово2&quot; date_add=&quot;2018-04-10T13:05:04&quot; date_modified=&quot;10.04.2018 20:54:46&quot; /&gt;
        ///    &lt;word id=&quot;3&quot; en=&quot;Word3&quot; ru=&quot;Слово3&quot; date_add=&quot;2018-04-10T13:05:04&quot; date_modified=&quot;10.04.2018 20:54:46&quot; /&gt;
        ///    &lt;word id=&quot;4&quot; en=&quot;Word4&quot; ru=&quot;Слово4&quot; date_add=&quot;2018-04-10T13:05:04&quot; date_modified=&quot;10.04.2018 20:54:46&quot; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string source_test5_dic {
            get {
                return ResourceManager.GetString("source_test5_dic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;library&gt;
        ///  &lt;GlobalDictionary&gt;
        ///    &lt;word id=&quot;1&quot; en=&quot;Word1&quot; ru=&quot;Слово1&quot; date_add=&quot;2018-04-10T13:05:04&quot; date_modified=&quot;10.04.2018 20:54:46&quot; /&gt;
        ///    &lt;word id=&quot;2&quot; en=&quot;Word2&quot; ru=&quot;Слово2&quot; date_add=&quot;2018-04-10T13:05:04&quot; date_modified=&quot;10.04.2018 20:54:46&quot; /&gt;
        ///    &lt;word id=&quot;3&quot; en=&quot;Word3&quot; ru=&quot;Слово3&quot; date_add=&quot;2018-04-10T13:05:04&quot; date_modified=&quot;10.04.2018 20:54:46&quot; /&gt;
        ///    &lt;word id=&quot;4&quot; en=&quot;Word4&quot; ru=&quot;Слово4&quot; date_add=&quot;2018-04-10T13:05:04&quot; date_modified=&quot;10.04.2018 20:54:46&quot; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string source_test6_dic {
            get {
                return ResourceManager.GetString("source_test6_dic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;library&gt;
        ///  &lt;GlobalDictionary&gt;
        ///    &lt;word id=&quot;1&quot; en=&quot;testing...&quot; ru=&quot;апробирование&quot; date_add=&quot;10.04.2018 13:05:04&quot; date_modified=&quot;10.04.2018 13:05:04&quot; /&gt;
        ///  &lt;/GlobalDictionary&gt;
        ///  &lt;PersonalDictionaries /&gt;
        ///  &lt;TraingProgressApplest /&gt;
        ///&lt;/library&gt;.
        /// </summary>
        internal static string test1_resoult {
            get {
                return ResourceManager.GetString("test1_resoult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;library&gt;
        ///  &lt;GlobalDictionary&gt;
        ///    &lt;word id=&quot;1&quot; en=&quot;EnWord1&quot; ru=&quot;EnWord2&quot; date_add=&quot;10.04.2018 13:05:04&quot; date_modified=&quot;10.04.2018 13:05:04&quot; /&gt;
        ///  &lt;/GlobalDictionary&gt;
        ///  &lt;PersonalDictionaries /&gt;
        ///  &lt;TraingProgressApplest /&gt;
        ///&lt;/library&gt;.
        /// </summary>
        internal static string test2_resoult {
            get {
                return ResourceManager.GetString("test2_resoult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;library&gt;
        ///  &lt;GlobalDictionary&gt;
        ///    &lt;word id=&quot;1&quot; en=&quot;Word1&quot; ru=&quot;Слово1&quot; date_add=&quot;10.04.2018 13:05:04&quot; date_modified=&quot;10.04.2018 13:05:04&quot; /&gt;
        ///    &lt;word id=&quot;4&quot; en=&quot;Word4&quot; ru=&quot;Слово4&quot; date_add=&quot;10.04.2018 13:05:04&quot; date_modified=&quot;10.04.2018 13:05:04&quot; /&gt;
        ///  &lt;/GlobalDictionary&gt;
        ///  &lt;PersonalDictionaries&gt;
        ///    &lt;dictionary name=&quot;dic1&quot; descr=&quot;descr1&quot; words=&quot;#1#4&quot; /&gt;
        ///    &lt;dictionary name=&quot;dic2&quot; descr=&quot;descr2&quot; words=&quot;#1#4&quot; /&gt;
        ///    &lt;dictionary name=&quot;dic3&quot; descr=&quot;descr3&quot; words [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string test4_resoult {
            get {
                return ResourceManager.GetString("test4_resoult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;library&gt;
        ///  &lt;GlobalDictionary&gt;
        ///    &lt;word id=&quot;1&quot; en=&quot;Word1&quot; ru=&quot;Слово1&quot; date_add=&quot;2018-04-10T13:05:04&quot; date_modified=&quot;10.04.2018 20:54:46&quot; /&gt;
        ///    &lt;word id=&quot;2&quot; en=&quot;Word2&quot; ru=&quot;Слово2&quot; date_add=&quot;2018-04-10T13:05:04&quot; date_modified=&quot;10.04.2018 20:54:46&quot; /&gt;
        ///    &lt;word id=&quot;3&quot; en=&quot;Word3&quot; ru=&quot;Слово3&quot; date_add=&quot;2018-04-10T13:05:04&quot; date_modified=&quot;10.04.2018 20:54:46&quot; /&gt;
        ///    &lt;word id=&quot;4&quot; en=&quot;Word4&quot; ru=&quot;Слово4&quot; date_add=&quot;2018-04-10T13:05:04&quot; date_modified=&quot;10.04.2018 20:54:46&quot; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string test5_resoult {
            get {
                return ResourceManager.GetString("test5_resoult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;library&gt;
        ///  &lt;GlobalDictionary&gt;
        ///    &lt;word id=&quot;1&quot; en=&quot;Word1&quot; ru=&quot;Слово1&quot; date_add=&quot;2018-04-10T13:05:04&quot; date_modified=&quot;10.04.2018 20:54:46&quot; /&gt;
        ///    &lt;word id=&quot;2&quot; en=&quot;Word2&quot; ru=&quot;Слово2&quot; date_add=&quot;2018-04-10T13:05:04&quot; date_modified=&quot;10.04.2018 20:54:46&quot; /&gt;
        ///    &lt;word id=&quot;3&quot; en=&quot;Word3&quot; ru=&quot;Слово3&quot; date_add=&quot;2018-04-10T13:05:04&quot; date_modified=&quot;10.04.2018 20:54:46&quot; /&gt;
        ///    &lt;word id=&quot;4&quot; en=&quot;Word4&quot; ru=&quot;Слово4&quot; date_add=&quot;2018-04-10T13:05:04&quot; date_modified=&quot;10.04.2018 20:54:46&quot; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string test6_resoult {
            get {
                return ResourceManager.GetString("test6_resoult", resourceCulture);
            }
        }
    }
}
